# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fb2b6dc3416418218ebc637097527356"
application_url = "https://knowledgestorm-notebooks-str-des.trycloudflare.com"
embedded = true
name = "remix-app"
handle = "remix-app-21"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_product_listings"

[auth]
redirect_urls = [
  "https://knowledgestorm-notebooks-str-des.trycloudflare.com/auth/callback",
  "https://knowledgestorm-notebooks-str-des.trycloudflare.com/auth/shopify/callback",
  "https://knowledgestorm-notebooks-str-des.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "urbann-curate.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
